// <auto-generated />
using Cake.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cake.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20220620092238_creat")]
    partial class creat
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Cake.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<string>("image")
                        .HasColumnName("ImageFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("price")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            id = 1,
                            description = "very good",
                            image = "cake.jpg",
                            name = "cake",
                            price = 100m
                        },
                        new
                        {
                            id = 2,
                            description = "very simple",
                            image = "baker.jpg",
                            name = "baker",
                            price = 10m
                        },
                        new
                        {
                            id = 3,
                            description = "very simple",
                            image = "baker.jpg",
                            name = "baker",
                            price = 122m
                        },
                        new
                        {
                            id = 4,
                            description = "very simple",
                            image = "a.jpg",
                            name = "baker",
                            price = 50m
                        },
                        new
                        {
                            id = 5,
                            description = "very simple",
                            image = "b.jpg",
                            name = "baker",
                            price = 60m
                        },
                        new
                        {
                            id = 6,
                            description = "very simple",
                            image = "c.jpg",
                            name = "baker",
                            price = 1000m
                        },
                        new
                        {
                            id = 7,
                            description = "very simple",
                            image = "d.jpg",
                            name = "baker",
                            price = 105m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
